"""Penalty constants mirrored from the backend Java code."""

FLIGHT_OVERLOAD_FACTOR_PER_DISTANCE = 5.0
UNFULFILLED_KIT_FACTOR_PER_DISTANCE = 0.003
INCORRECT_FLIGHT_LOAD = 5000.0
NEGATIVE_INVENTORY = 5342.0
OVER_CAPACITY_STOCK = 777.0
END_OF_GAME_REMAINING_STOCK = 0.0013
EARLY_END_OF_GAME = 1000.0
END_OF_GAME_PENDING_KIT_PROCESSING = 0.0013
END_OF_GAME_UNFULFILLED_FLIGHT_KITS = 1.5
